# Portfolio assignment 5
20 min: 
- Download lifeExpectancyAtBirth.csv from Brightspace ([original source](https://www.kaggle.com/utkarshxy/who-worldhealth-statistics-2020-complete?select=lifeExpectancyAtBirth.csv)).
- Move the file to the same folder as the Notebook that you will be working in.
- Load the dataset in your Notebook with the following code: lifeExpectancy = pd.read_csv('lifeExpectancyAtBirth.csv', sep=',')
- Look at the dataset with the .head() function.
- Filter the dataframe: We only want the life expectancy data about 2019 and 'Both sexes'
- Use this dataframe to perform a univariate analysis on the life expectancy in 2019.
- Which five countries have the highest life expectancy? Which five the lowest?

Commit the notebook and dataset to your portfolio when you're finished.

In [2]:
import pandas as pd

In [4]:
lifeExpectancy = pd.read_csv('lifeExpectancyAtBirth.csv', sep=',')

In [21]:
lifeExpectancy.head()

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Life expectancy at birth (years),Both sexes,63.21
1,Afghanistan,2019,Life expectancy at birth (years),Male,63.29
2,Afghanistan,2019,Life expectancy at birth (years),Female,63.16
3,Afghanistan,2019,Life expectancy at birth (years),Both sexes,61.65
4,Afghanistan,2019,Life expectancy at birth (years),Male,61.04

In [15]:
filter1 = lifeExpectancy['Period'] == 2019
filter2 = lifeExpectancy['Dim1'] == "Both sexes"
lifeExpectancy[filter1 & filter2]

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Life expectancy at birth (years),Both sexes,63.21
3,Afghanistan,2019,Life expectancy at birth (years),Both sexes,61.65
6,Afghanistan,2019,Life expectancy at birth (years),Both sexes,59.94
9,Afghanistan,2019,Life expectancy at birth (years),Both sexes,54.99
12,Albania,2019,Life expectancy at birth (years),Both sexes,78.00
...,...,...,...,...,...
2182,Zambia,2019,Life expectancy at birth (years),Both sexes,44.46
2185,Zimbabwe,2019,Life expectancy at birth (years),Both sexes,60.68
2188,Zimbabwe,2019,Life expectancy at birth (years),Both sexes,58.48
2191,Zimbabwe,2019,Life expectancy at birth (years),Both sexes,51.49
2194,Zimbabwe,2019,Life expectancy at birth (years),Both sexes,46.57

In [16]:
lifeExpectancy['Location'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo', 'Costa Rica', 'CÃ´te dâ€™Ivoire',
       'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran (Islamic Republic of)',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Micronesia (Federated States of)',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Republic of Korea', 'Republic of Moldova',
       'The former Yugoslav Republic of Macedonia', 'Romania',
       'Russian Federation', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (until 2011)', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine',
       'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

In [25]:
lifeExpectancy[filter1]

,Location,Period,Indicator,Dim1,First Tooltip
0,Afghanistan,2019,Life expectancy at birth (years),Both sexes,63.21
1,Afghanistan,2019,Life expectancy at birth (years),Male,63.29
2,Afghanistan,2019,Life expectancy at birth (years),Female,63.16
3,Afghanistan,2019,Life expectancy at birth (years),Both sexes,61.65
4,Afghanistan,2019,Life expectancy at birth (years),Male,61.04
...,...,...,...,...,...
2192,Zimbabwe,2019,Life expectancy at birth (years),Male,49.58
2193,Zimbabwe,2019,Life expectancy at birth (years),Female,53.21
2194,Zimbabwe,2019,Life expectancy at birth (years),Both sexes,46.57
2195,Zimbabwe,2019,Life expectancy at birth (years),Male,45.15
2196,Zimbabwe,2019,Life expectancy at birth (years),Female,48.12